// styles/coffeeStyles.js
export const styles = {
  app: {
    fontFamily: "'DM Sans', sans-serif",
    background: 'linear-gradient(135deg, #FAFAFA 0%, #F0EBE6 100%)',
    minHeight: '100vh',
    color: '#1A1A1A',
  },
  
  // Hero
  hero: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4rem 2rem',
    position: 'relative',
    overflow: 'hidden',
    flexDirection: 'column',
  },
  heroContainer: {
    maxWidth: '1400px',
    width: '100%',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '4rem',
    alignItems: 'center',
  },
  heroContent: {
    maxWidth: '600px',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    background: 'white',
    padding: '0.5rem 1.25rem',
    borderRadius: '50px',
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#6F4E37',
    boxShadow: '0 4px 20px rgba(0,0,0,0.1)',
    marginBottom: '2rem',
  },
  heroTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 'clamp(2.5rem, 6vw, 4.5rem)',
    fontWeight: '800',
    lineHeight: '1.1',
    marginBottom: '1.5rem',
    color: '#1A1A1A',
  },
  highlight: {
    color: '#6F4E37',
    position: 'relative',
  },
  heroSubtitle: {
    fontSize: '1.25rem',
    lineHeight: '1.8',
    color: '#666',
    marginBottom: '3rem',
  },
  ctaGroup: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
  },
  btnPrimary: {
    padding: '1rem 2.5rem',
    background: '#512da8',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontWeight: '600',
    fontSize: '1rem',
    cursor: 'pointer',
    boxShadow: '0 10px 30px rgba(81, 45, 168, 0.3)',
    transition: 'all 0.3s',
  },
  
  // Mockup
  mockupContainer: {
    position: 'relative',
    perspective: '1000px',
  },
  scene: {
    position: 'relative',
    width: '100%',
    height: '600px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  phone: {
    position: 'relative',
    width: '280px',
    height: '580px',
    background: '#1A1A1A',
    borderRadius: '40px',
    padding: '12px',
    boxShadow: '0 50px 100px rgba(0, 0, 0, 0.25), 0 20px 40px rgba(0, 0, 0, 0.15)',
    transform: 'rotateY(-15deg) rotateX(5deg)',
    zIndex: 2,
  },
  phoneScreen: {
    width: '100%',
    height: '100%',
    background: 'linear-gradient(135deg, #FFFFFF 0%, #F8F8F8 100%)',
    borderRadius: '32px',
    overflow: 'hidden',
    boxShadow: 'inset 0 2px 10px rgba(0, 0, 0, 0.05)',
  },
  screenContent: {
    padding: '3rem 2rem',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  coffeeIcon: {
    fontSize: '4rem',
    marginBottom: '1rem',
  },
  screenTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: '1.75rem',
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: '0.5rem',
  },
  screenSubtitle: {
    fontSize: '0.875rem',
    color: '#666',
    marginBottom: '2rem',
  },
  donationAmounts: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '0.75rem',
    width: '100%',
    marginBottom: '1.5rem',
  },
  amountBtn: {
    background: 'white',
    border: '2px solid #E0E0E0',
    padding: '1rem',
    borderRadius: '12px',
    fontWeight: '600',
    color: '#1A1A1A',
    cursor: 'pointer',
    fontSize: '0.9rem',
    transition: 'all 0.3s',
  },
  amountBtnActive: {
    borderColor: '#512da8',
    background: '#512da8',
    color: 'white',
  },
  sendBtn: {
    width: '100%',
    background: '#512da8',
    color: 'white',
    border: 'none',
    padding: '1rem',
    borderRadius: '12px',
    fontWeight: '600',
    fontSize: '1rem',
  },
  
  // Coffee Cup
  coffeeCup: {
    position: 'absolute',
    bottom: '50px',
    right: '-100px',
    width: '180px',
    height: '180px',
    zIndex: 1,
  },
  steam: {
    position: 'absolute',
    top: '-30px',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '5px',
  },
  steamSpan: {
    display: 'block',
    width: '3px',
    height: '30px',
    background: 'linear-gradient(to top, transparent, rgba(111, 78, 55, 0.3))',
    borderRadius: '50%',
    opacity: 0,
  },
  cupBody: {
    width: '140px',
    height: '160px',
    background: 'linear-gradient(135deg, #FFFFFF 0%, #F5F1ED 100%)',
    borderRadius: '0 0 70px 70px',
    position: 'relative',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.15)',
  },
  cupHandle: {
    position: 'absolute',
    right: '-35px',
    top: '40px',
    width: '50px',
    height: '70px',
    border: '15px solid #FFFFFF',
    borderLeft: 'none',
    borderRadius: '0 50px 50px 0',
    boxShadow: 'inset -3px 0 8px rgba(0, 0, 0, 0.1), 0 5px 15px rgba(0, 0, 0, 0.1)',
  },
  
  // Stats
  stats: {
    display: 'flex',
    gap: '3rem',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginTop: '4rem',
  },
  statItem: {
    textAlign: 'center',
  },
  statNumber: {
    fontFamily: "'Playfair Display', serif",
    fontSize: '2.5rem',
    fontWeight: '700',
    color: '#512da8',
    lineHeight: '1',
    marginBottom: '0.25rem',
  },
  statLabel: {
    fontSize: '0.875rem',
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  
  // Campaigns Section
  campaignsSection: {
    padding: '6rem 2rem',
    background: 'white',
  },
  sectionHeader: {
    maxWidth: '1400px',
    margin: '0 auto 4rem',
    textAlign: 'center',
  },
  sectionTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 'clamp(2rem, 4vw, 3rem)',
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: '1rem',
  },
  sectionDescription: {
    fontSize: '1.125rem',
    color: '#666',
  },
  
  // Filters
  filterTabs: {
    maxWidth: '1400px',
    margin: '0 auto 3rem',
    display: 'flex',
    gap: '1rem',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  filterTab: {
    padding: '0.75rem 1.5rem',
    background: '#F5F1ED',
    border: 'none',
    borderRadius: '50px',
    fontWeight: '600',
    color: '#666',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  filterTabActive: {
    background: '#512da8',
    color: 'white',
  },
  
  // Campaign Grid
  campaignsGrid: {
    maxWidth: '1400px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
    gap: '2rem',
  },
  
  // Campaign Card
  card: {
    background: 'white',
    borderRadius: '20px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
    transition: 'all 0.4s',
    cursor: 'pointer',
    border: '2px solid transparent',
  },
  cardHeader: {
    padding: '1.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    borderBottom: '1px solid #F0EBE6',
  },
  avatar: {
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #512da8, #7c4dff)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    flexShrink: 0,
  },
  cardInfo: {
    flex: 1,
  },
  cardName: {
    fontWeight: '700',
    fontSize: '1.125rem',
    color: '#1A1A1A',
    marginBottom: '0.25rem',
  },
  cardType: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    fontSize: '0.875rem',
    padding: '0.25rem 0.75rem',
    borderRadius: '50px',
  },
  cardTypeCharity: {
    background: '#FEE2E2',
    color: '#991B1B',
  },
  cardTypeCreator: {
    background: '#E9D5FF',
    color: '#6B21A8',
  },
  cardBody: {
    padding: '1.5rem',
  },
  description: {
    color: '#666',
    lineHeight: '1.6',
    marginBottom: '1.5rem',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  timeRemaining: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.75rem',
    background: '#FEF3C7',
    borderRadius: '10px',
    marginBottom: '1rem',
  },
  timeUrgent: {
    background: '#FEE2E2',
  },
  timeIcon: {
    fontSize: '1.25rem',
  },
  timeText: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#1A1A1A',
  },
  progressSection: {
    marginBottom: '1rem',
  },
  progressStats: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '0.5rem',
    fontSize: '0.875rem',
  },
  progressLabel: {
    color: '#666',
  },
  progressAmount: {
    fontWeight: '700',
    color: '#512da8',
  },
  progressBarContainer: {
    height: '8px',
    background: '#F0EBE6',
    borderRadius: '10px',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    background: 'linear-gradient(90deg, #512da8, #7c4dff)',
    borderRadius: '10px',
    transition: 'width 1s ease-out',
  },
  cardFooter: {
    padding: '1.5rem',
    background: '#FAFAFA',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  supporters: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  supportersAvatars: {
    display: 'flex',
  },
  miniAvatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #10B981, #059669)',
    border: '2px solid white',
    marginLeft: '-8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.7rem',
  },
  supportersCount: {
    fontSize: '0.875rem',
    color: '#666',
    marginLeft: '0.25rem',
  },
  donateBtn: {
    padding: '0.75rem 1.5rem',
    background: '#512da8',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  
  // Detail View
  detailContainer: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '4rem 2rem',
  },
  backButton: {
    background: 'none',
    border: 'none',
    fontSize: '1rem',
    color: '#666',
    cursor: 'pointer',
    padding: '0.5rem 0',
    marginBottom: '3rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1.5fr',
    gap: '4rem',
  },
  detailImageSection: {
    position: 'sticky',
    top: '2rem',
    height: 'fit-content',
  },
  detailImage: {
    width: '100%',
    paddingTop: '100%',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    borderRadius: '20px',
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  detailInfo: {},
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  detailAvatar: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #512da8, #7c4dff)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '2.5rem',
    flexShrink: 0,
  },
  detailName: {
    fontFamily: "'Playfair Display', serif",
    fontSize: '2.5rem',
    fontWeight: '700',
    margin: '0 0 0.5rem',
    letterSpacing: '-0.02em',
  },
  detailType: {
    fontSize: '0.875rem',
    padding: '0.5rem 1rem',
    borderRadius: '50px',
    display: 'inline-block',
  },
  detailTypeCreator: {
    background: '#E9D5FF',
    color: '#6B21A8',
  },
  detailTypeCharity: {
    background: '#FEE2E2',
    color: '#991B1B',
  },
  detailDescription: {
    fontSize: '1.125rem',
    lineHeight: '1.8',
    color: '#333',
    marginBottom: '2rem',
  },
  detailWallet: {
    padding: '1.5rem',
    background: '#F9FAFB',
    borderRadius: '12px',
    marginBottom: '2rem',
  },
  detailWalletLabel: {
    display: 'block',
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: '#999',
    marginBottom: '0.75rem',
    fontWeight: '600',
  },
  detailWalletAddress: {
    fontSize: '0.875rem',
    fontFamily: 'monospace',
    color: '#512da8',
    wordBreak: 'break-all',
    background: 'white',
    padding: '0.75rem',
    borderRadius: '6px',
    display: 'block',
  },
  detailStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  detailStatItem: {
    textAlign: 'center',
    padding: '1.5rem',
    background: '#F9FAFB',
    borderRadius: '12px',
  },
  detailStatNumber: {
    fontFamily: "'Playfair Display', serif",
    fontSize: '2rem',
    fontWeight: '700',
    color: '#512da8',
    marginBottom: '0.5rem',
  },
  detailStatLabel: {
    fontSize: '0.875rem',
    color: '#666',
  },
  detailDonateBtn: {
    width: '100%',
    padding: '1.25rem',
    background: '#512da8',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '1.125rem',
    fontWeight: '600',
    cursor: 'pointer',
    marginBottom: '3rem',
    boxShadow: '0 10px 30px rgba(81, 45, 168, 0.3)',
    transition: 'all 0.3s',
  },
  
  // Recent Donations
  recentDonations: {
    borderTop: '2px solid #F0EBE6',
    paddingTop: '2rem',
  },
  recentTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: '1.5rem',
    fontWeight: '700',
    margin: '0 0 1.5rem',
  },
  donationsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  donationItem: {
    padding: '1.25rem',
    background: '#F9FAFB',
    borderRadius: '12px',
    border: '1px solid #F0EBE6',
    transition: 'all 0.3s',
  },
  donationTop: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '0.5rem',
    alignItems: 'center',
  },
  donationFrom: {
    fontSize: '0.875rem',
    fontFamily: 'monospace',
    color: '#666',
  },
  donationAmount: {
    fontSize: '1rem',
    fontWeight: '700',
    color: '#512da8',
  },
  donationMessage: {
    fontSize: '0.9375rem',
    fontStyle: 'italic',
    color: '#333',
    margin: '0.75rem 0',
    lineHeight: '1.6',
  },
  donationTime: {
    fontSize: '0.75rem',
    color: '#999',
  },
  noDonations: {
    fontSize: '0.9375rem',
    color: '#999',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '2rem',
  },
  
  // Modals
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '2rem',
  },
  modal: {
    background: 'white',
    borderRadius: '24px',
    maxWidth: '500px',
    width: '100%',
    maxHeight: '90vh',
    overflow: 'auto',
    position: 'relative',
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
  },
  closeBtn: {
    position: 'absolute',
    top: '1.5rem',
    right: '1.5rem',
    background: '#F5F1ED',
    border: 'none',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    fontSize: '1.5rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s',
    color: '#666',
    zIndex: 10,
  },
  modalHeader: {
    padding: '3rem 2rem 1.5rem',
    textAlign: 'center',
    borderBottom: '1px solid #F0EBE6',
  },
  modalAvatar: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #512da8, #7c4dff)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '2.5rem',
    margin: '0 auto 1rem',
  },
  modalTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: '1.75rem',
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: '0.5rem',
  },
  modalSubtitle: {
    fontSize: '0.9375rem',
    color: '#666',
  },
  modalBody: {
    padding: '2rem',
  },
  form: {
    padding: '2rem',
  },
  formGroup: {
    marginBottom: '1.5rem',
  },
  label: {
    display: 'block',
    marginBottom: '0.5rem',
    fontWeight: '600',
    color: '#1A1A1A',
    fontSize: '0.875rem',
  },
  input: {
    width: '100%',
    padding: '1rem',
    border: '2px solid #E0E0E0',
    borderRadius: '12px',
    fontSize: '1rem',
    transition: 'all 0.3s',
    fontFamily: 'inherit',
  },
  textarea: {
    width: '100%',
    padding: '1rem',
    border: '2px solid #E0E0E0',
    borderRadius: '12px',
    fontSize: '1rem',
    minHeight: '100px',
    resize: 'vertical',
    fontFamily: 'inherit',
    transition: 'all 0.3s',
  },
  hint: {
    fontSize: '0.75rem',
    color: '#999',
    marginTop: '0.5rem',
    display: 'block',
  },
  quickAmounts: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  quickBtn: {
    padding: '0.75rem',
    background: 'white',
    border: '2px solid #E0E0E0',
    borderRadius: '10px',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  quickBtnActive: {
    background: '#512da8',
    color: 'white',
    borderColor: '#512da8',
  },
  walletWarning: {
    padding: '1rem',
    background: '#FEF3C7',
    borderRadius: '10px',
    marginBottom: '1rem',
    textAlign: 'center',
    fontWeight: '600',
    color: '#92400E',
    fontSize: '0.875rem',
  },
  submitBtn: {
    width: '100%',
    padding: '1rem',
    background: '#512da8',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  donateButton: {
    width: '100%',
    padding: '1rem',
    background: '#512da8',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  status: {
    marginTop: '1rem',
    padding: '1rem',
    background: '#F5F1ED',
    borderRadius: '10px',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: '0.875rem',
  },
};